### ISSUE TITLE
deploy之后我的网页404

### ISSUE THREAD

**Issue by Wentaobi** [loyayz/loyayz.github.io#1]
步骤：
本仓库使用 git submodule 引用主题仓库，因此 git clone 本仓库后需要再执行下命令

git submodule update --init --recursive

[wentaobi.github.io/frank](https://wentaobi.github.io/frank)

**Comment by loyayz** [comment]
基于[Github Pages](https://pages.github.com/)部署的。你这个带上下文的，我也不清楚怎么设置，你可以在仓库的`Settings`下的`Pages`看看帮助文档。
